### ISSUE TITLE
uninitialized constant BetterErrors::Middleware::VERSION (NameError)

### ISSUE THREAD

**Issue by seb-sykio** [BetterErrors/better_errors#483] opened 2020-10-02 09:05 UTC
3: from .rvm/gems/ruby-2.6.5/gems/better_errors-2.8.2/lib/better_errors.rb:9:in `<top (required)>'
	 2: from .rvm/gems/ruby-2.6.5/gems/better_errors-2.8.2/lib/better_errors/middleware.rb:7:in `<top (required)>'
	 1: from .rvm/gems/ruby-2.6.5/gems/better_errors-2.8.2/lib/better_errors/middleware.rb:28:in `<module:BetterErrors>'
.rvm/gems/ruby-2.6.5/gems/better_errors-2.8.2/lib/better_errors/middleware.rb:43:in `<class:Middleware>': uninitialized constant BetterErrors::Middleware::VERSION (NameError)

ruby 2.6
rails 4.2.11.3

**Comment by frobert** [comment] 2020-10-02 09:09
Same here after update :/

**Comment by joker-777** [comment] 2020-10-02 09:15
Same for me!

**Comment by frobert** [comment] 2020-10-02 09:55
Duplicate of https://github.com/BetterErrors/better_errors/issues/482

**Comment by afuno** [comment] 2020-10-02 10:52
Same

**Comment by jcoglan** [comment] 2020-10-02 13:27
I believe this change is the source of the problem: referring to `VERSION` without having explicitly loaded that constant. It's stopping our Rails app from booting.

https://github.com/BetterErrors/better_errors/compare/v2.8.1..master#diff-5e3c1d57ea649185a86b730f951f5a18R43

**Comment by addisonmartin** [comment] 2020-10-02 19:46
I've submitted a fix:
https://github.com/BetterErrors/better_errors/pull/480

**Comment by RobinDaugherty** [comment] 2020-10-03 03:35
Very sorry for my mistake everyone, release 2.8.3 fixes this and is live (and I tested it in an app). Thank you @addisonmartin and @peaonunes for the PRs!

**Closed by RobinDaugherty** 2020-10-03 03:35 UTC
